/// Flutter icons GNIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GNIcons
///      fonts:
///       - asset: fonts/GNIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GNIcons {
  GNIcons._();

  static const _kFontFam = 'GNIcons';
  static const String? _kFontPkg = null;

  static const IconData capicon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoppericon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData searchicon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usericon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
