/// Flutter icons Paint
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Paint
///      fonts:
///       - asset: fonts/Paint.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PaintIcon {
  PaintIcon._();

  static const _kFontFam = 'Paint';
  static const String? _kFontPkg = null;

  static const IconData paint =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
