name: graffitineeds
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  pull_to_refresh_flutter3: ^2.0.1
  flutter_html: ^3.0.0-alpha.6
  infinite_scroll_pagination: ^3.1.0
  uuid: ^3.0.5
  intl: ^0.18.1
  url_launcher: ^6.0.12
  flutter_local_notifications: ^12.0.0
  provider: ^6.0.2
  firebase_core: ^2.9.0
  carousel_slider: ^4.1.1
  top_snackbar_flutter: ^2.1.1
  sliver_tools: ^0.2.5
  skeleton_loader: ^2.0.0+4
  expandable: ^5.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  logging: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hex: ^0.2.0
  http: ^0.13.4
  flutter_neumorphic: 
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  motion_toast: ^2.1.2
  golden_toolkit: ^0.13.0
  package_info_plus: ^3.0.2
  equatable: ^2.0.3
  loading_animation_widget: ^1.2.0+2
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.0.1
  requests: ^4.2.1
  flutter_cache_manager: ^3.3.1
  octo_image: ^2.0.0
  connection_notifier: ^0.0.1
  intl_phone_number_input: ^0.7.2
  pinput: ^2.2.21
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet





  

dev_dependencies:

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/socials/

  fonts:
    - family: GNIcons
      fonts:
        - asset: lib/assets/fonts/GNIcons.ttf
    - family: Circe
      fonts:
        - asset: lib/assets/fonts/Circe-Regular.ttf
        - asset: lib/assets/fonts/Circe-Bold.ttf
        - asset: lib/assets/fonts/Circe-ExtraBold.ttf
        - asset: lib/assets/fonts/Circe-ExtraLight.ttf
        - asset: lib/assets/fonts/Circe-Light.ttf
    - family:  Paint
      fonts:
        - asset: lib/assets/fonts/Paint.ttf      
          

 